// <auto-generated />
namespace NguyenTheAnh_03.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class NhanViens : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NhanViens));
        
        string IMigrationMetadata.Id
        {
            get { return "202106060841218_NhanViens"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
